# Generated by Django 5.0.2 on 2024-03-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightNumber', models.CharField(max_length=10)),
                ('operatingAirline', models.CharField(max_length=20)),
                ('DepartureCity', models.CharField(max_length=20)),
                ('arrivalCity', models.CharField(max_length=20)),
                ('dateOfDeparture', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='passengerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='reservationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserve_flight.flightmodel')),
                ('passenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserve_flight.passengermodel')),
            ],
        ),
    ]
