# Generated by Django 5.0.2 on 2024-03-13 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve_flight.flightmodel'),
        ),
    ]
