# Generated by Django 5.0.2 on 2024-03-13 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_flight', '0002_alter_reservationmodel_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reserve_flight.flightmodel'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='reserve_flight.passengermodel'),
        ),
    ]
